# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: run
      run: go run -v .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
    # Artifact name
        name: test
    # A file, directory or wildcard pattern that describes what to upload
        path: ./scripts
    # The desired behavior if no files are found using the provided path.
